# Generated by Django 5.0.7 on 2024-08-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='food_item',
            new_name='product',
        ),
    ]
