# Generated by Django 5.0.7 on 2024-08-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'tax'},
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Tax Percentage (%)'),
        ),
    ]
