# Generated by Django 5.0.7 on 2024-08-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_tax_options_alter_tax_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax Percentage (%)'),
        ),
    ]
