# Generated by Django 5.0.7 on 2024-08-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_licence',
            new_name='vendor_license',
        ),
    ]
