# Generated by Django 5.0.7 on 2024-08-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_openinghours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ('day', '-from_hour')},
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('vendor', 'day', 'from_hour', 'to_hour')},
        ),
    ]
