# Generated by Django 5.0.7 on 2024-08-19 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_openinghours_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='vendors.vendor'),
        ),
    ]
