# Generated by Django 5.0.7 on 2024-08-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pin_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='province',
        ),
    ]
