# Generated by Django 5.0.7 on 2024-08-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_pin_code_order_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='fooditem',
            new_name='product',
        ),
    ]
